/**
 * Internal world sound profiles — hidden synthesis recipes per territory.
 * NES / Amiga character; not exposed as user knobs.
 */

/** @typedef {Object} WorldSoundProfile
 * @property {string} id
 * @property {OscillatorType|null} oscA
 * @property {OscillatorType|null} oscB
 * @property {number} oscAGain
 * @property {number} oscBGain
 * @property {number} oscBDetuneCents
 * @property {number} harmonicRatio
 * @property {number} harmonicGain
 * @property {number} attackMs
 * @property {number} releaseMs
 * @property {number} envelopeTight
 * @property {number} filterCutoffHz
 * @property {number} filterQ
 * @property {number} filterEnvAmount
 * @property {number} filterCutoffStart
 * @property {number} filterCutoffEnd
 * @property {number} filterEnvAttackMs
 * @property {number} satAmount
 * @property {number} chorusDepth
 * @property {number} chorusRate
 * @property {number} chorusMix
 * @property {number} delayTimeMs
 * @property {number} delayFeedback
 * @property {number} delayMix
 * @property {number} stereoWidth
 * @property {number|null} toneBias
 */

/** @type {WorldSoundProfile} */
export const DEFAULT_SOUND_PROFILE = {
  id: 'custom',
  oscA: null,
  oscB: 'triangle',
  oscAGain: 0.7,
  oscBGain: 0.22,
  oscBDetuneCents: 3,
  harmonicRatio: 0,
  harmonicGain: 0,
  attackMs: 10,
  releaseMs: 58,
  envelopeTight: 0.5,
  filterCutoffHz: 11800,
  filterQ: 0.62,
  filterEnvAmount: 0.28,
  filterCutoffStart: 0.62,
  filterCutoffEnd: 1,
  filterEnvAttackMs: 42,
  satAmount: 0.1,
  chorusDepth: 0.0028,
  chorusRate: 0.55,
  chorusMix: 0.12,
  delayTimeMs: 92,
  delayFeedback: 0.13,
  delayMix: 0.05,
  stereoWidth: 0.1,
  toneBias: null,
};

/** @type {Record<string, Partial<WorldSoundProfile> & { id: string }>} */
const WORLD_OVERRIDES = {
  beach: {
    id: 'beach',
    oscA: 'sine',
    oscB: 'triangle',
    oscAGain: 0.68,
    oscBGain: 0.32,
    oscBDetuneCents: -2.8,
    attackMs: 13,
    releaseMs: 76,
    envelopeTight: 0.35,
    filterCutoffHz: 9200,
    filterQ: 0.55,
    filterEnvAmount: 0.42,
    filterCutoffStart: 0.48,
    filterCutoffEnd: 1,
    filterEnvAttackMs: 68,
    satAmount: 0.06,
    chorusDepth: 0.0042,
    chorusRate: 0.42,
    chorusMix: 0.2,
    delayTimeMs: 112,
    delayFeedback: 0.15,
    delayMix: 0.075,
    stereoWidth: 0.16,
    toneBias: 0.12,
  },
  'ice-cave': {
    id: 'ice-cave',
    oscA: 'square',
    oscB: 'sine',
    oscAGain: 0.52,
    oscBGain: 0.22,
    oscBDetuneCents: 8.5,
    harmonicRatio: 3,
    harmonicGain: 0.44,
    attackMs: 2,
    releaseMs: 42,
    envelopeTight: 0.86,
    filterCutoffHz: 16800,
    filterQ: 0.32,
    filterEnvAmount: 0.78,
    filterCutoffStart: 0.88,
    filterCutoffEnd: 1.22,
    filterEnvAttackMs: 6,
    satAmount: 0.03,
    chorusDepth: 0.0012,
    chorusRate: 0.72,
    chorusMix: 0.03,
    delayTimeMs: 52,
    delayFeedback: 0.06,
    delayMix: 0.018,
    stereoWidth: 0.24,
    toneBias: 0.04,
  },
  arcade: {
    id: 'arcade',
    oscA: 'square',
    oscB: 'square',
    oscAGain: 0.82,
    oscBGain: 0.14,
    oscBDetuneCents: 6.2,
    attackMs: 3,
    releaseMs: 32,
    envelopeTight: 0.94,
    filterCutoffHz: 11200,
    filterQ: 0.78,
    filterEnvAmount: 0.68,
    filterCutoffStart: 0.28,
    filterCutoffEnd: 1.12,
    filterEnvAttackMs: 10,
    satAmount: 0.22,
    chorusDepth: 0.0008,
    chorusRate: 0.9,
    chorusMix: 0.02,
    delayTimeMs: 48,
    delayFeedback: 0.06,
    delayMix: 0.018,
    stereoWidth: 0.04,
    toneBias: 0.68,
  },
  speedway: {
    id: 'speedway',
    oscA: 'sawtooth',
    oscB: 'square',
    oscAGain: 0.8,
    oscBGain: 0.18,
    oscBDetuneCents: -5.2,
    attackMs: 4,
    releaseMs: 38,
    envelopeTight: 0.94,
    filterCutoffHz: 9800,
    filterQ: 0.72,
    filterEnvAmount: 0.58,
    filterCutoffStart: 0.28,
    filterCutoffEnd: 1.05,
    filterEnvAttackMs: 11,
    satAmount: 0.24,
    chorusDepth: 0.001,
    chorusRate: 1.05,
    chorusMix: 0.02,
    delayTimeMs: 52,
    delayFeedback: 0.05,
    delayMix: 0.015,
    stereoWidth: 0.06,
    toneBias: 0.82,
  },
  'space-age': {
    id: 'space-age',
    oscA: 'sine',
    oscB: 'sine',
    oscAGain: 0.52,
    oscBGain: 0.42,
    oscBDetuneCents: -7.2,
    harmonicRatio: 1.5,
    harmonicGain: 0.08,
    attackMs: 14,
    releaseMs: 88,
    envelopeTight: 0.32,
    filterCutoffHz: 12200,
    filterQ: 0.48,
    filterEnvAmount: 0.28,
    filterCutoffStart: 0.62,
    filterCutoffEnd: 1.04,
    filterEnvAttackMs: 72,
    satAmount: 0.05,
    chorusDepth: 0.0058,
    chorusRate: 0.38,
    chorusMix: 0.24,
    delayTimeMs: 118,
    delayFeedback: 0.1,
    delayMix: 0.048,
    stereoWidth: 0.42,
    toneBias: 0.04,
  },
  dungeon: {
    id: 'dungeon',
    oscA: 'triangle',
    oscB: 'sine',
    oscAGain: 0.72,
    oscBGain: 0.2,
    oscBDetuneCents: -2.2,
    attackMs: 11,
    releaseMs: 68,
    envelopeTight: 0.55,
    filterCutoffHz: 5200,
    filterQ: 0.72,
    filterEnvAmount: 0.32,
    filterCutoffStart: 0.42,
    filterCutoffEnd: 0.82,
    filterEnvAttackMs: 55,
    satAmount: 0.14,
    chorusDepth: 0.002,
    chorusRate: 0.35,
    chorusMix: 0.08,
    delayTimeMs: 98,
    delayFeedback: 0.16,
    delayMix: 0.06,
    stereoWidth: 0.08,
    toneBias: 0.22,
  },
  bubble: {
    id: 'bubble',
    oscA: 'sine',
    oscB: 'triangle',
    oscAGain: 0.74,
    oscBGain: 0.32,
    oscBDetuneCents: 2.8,
    harmonicRatio: 0,
    harmonicGain: 0,
    attackMs: 18,
    releaseMs: 72,
    envelopeTight: 0.28,
    filterCutoffHz: 8800,
    filterQ: 0.42,
    filterEnvAmount: 0.32,
    filterCutoffStart: 0.42,
    filterCutoffEnd: 0.96,
    filterEnvAttackMs: 58,
    satAmount: 0.04,
    chorusDepth: 0.0038,
    chorusRate: 0.48,
    chorusMix: 0.14,
    delayTimeMs: 72,
    delayFeedback: 0.08,
    delayMix: 0.032,
    stereoWidth: 0.14,
    toneBias: 0.08,
  },
  desert: {
    id: 'desert',
    oscA: 'triangle',
    oscB: 'sine',
    oscAGain: 0.74,
    oscBGain: 0.12,
    oscBDetuneCents: 1.2,
    attackMs: 8,
    releaseMs: 52,
    envelopeTight: 0.68,
    filterCutoffHz: 5200,
    filterQ: 0.72,
    filterEnvAmount: 0.14,
    filterCutoffStart: 0.52,
    filterCutoffEnd: 0.72,
    filterEnvAttackMs: 38,
    satAmount: 0.09,
    chorusDepth: 0.0006,
    chorusRate: 0.28,
    chorusMix: 0.008,
    delayTimeMs: 42,
    delayFeedback: 0.04,
    delayMix: 0.008,
    stereoWidth: 0.06,
    toneBias: 0.24,
  },
  disco: {
    id: 'arcade',
    oscA: 'square',
    oscB: 'square',
    oscAGain: 0.82,
    oscBGain: 0.14,
    oscBDetuneCents: 6.2,
    attackMs: 3,
    releaseMs: 32,
    envelopeTight: 0.94,
    filterCutoffHz: 11200,
    filterQ: 0.78,
    filterEnvAmount: 0.68,
    filterCutoffStart: 0.28,
    filterCutoffEnd: 1.12,
    filterEnvAttackMs: 10,
    satAmount: 0.22,
    chorusDepth: 0.0008,
    chorusRate: 0.9,
    chorusMix: 0.02,
    delayTimeMs: 48,
    delayFeedback: 0.06,
    delayMix: 0.018,
    stereoWidth: 0.04,
    toneBias: 0.68,
  },
};

/**
 * @param {string|null|undefined} worldKey
 * @returns {WorldSoundProfile}
 */
export function resolveSoundProfile(worldKey) {
  if (!worldKey) return { ...DEFAULT_SOUND_PROFILE };
  const key = worldKey === 'disco' ? 'arcade' : worldKey;
  const overrides = WORLD_OVERRIDES[key];
  return overrides
    ? { ...DEFAULT_SOUND_PROFILE, ...overrides }
    : { ...DEFAULT_SOUND_PROFILE };
}
